module:
  description: Ingress controller for garden development
  name: ingress-controller
  type: helm
  chart: stable/nginx-ingress
  version: 0.25.1
  parameters:
    name: ingress-controller
    controller:
      kind: DaemonSet
      daemonset:
        useHostPort: true
