module:
  description: Ingress controller for garden development
  name: ingress-controller
  type: helm
  chart: stable/nginx-ingress
  dependencies:
    - default-backend
  version: 0.25.1
  parameters:
    name: ingress-controller
    controller:
      defaultBackendService: garden-system/default-backend
      kind: DaemonSet
      daemonset:
        useHostPort: true
    defaultBackend:
      enabled: false
